### ISSUE TITLE
failed to build with torch 1.9.0

### ISSUE THREAD

**Issue by qiuxiafei** [alibaba/BladeDISC#534]
It reports:
```
src/compiler/jit/torch/shape_analysis.cpp:1773:53: error: 'struct c10::ShapeSymbol' has no member named 'value'; did you mean 'value_'?
```
